# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_ROTATELOCK)	+= rotationlock_switch.o
obj-$(CONFIG_DOCK_V1)		+= acer_dock_v1.o
obj-$(CONFIG_DOCK_V2)		+= acer_dock_v2.o
obj-$(CONFIG_PSENSOR3G)		+= psensor_switch_3g.o
obj-$(CONFIG_SIMDETECT) +=  simdetect_switch.o
obj-$(CONFIG_PSENSOR)		+= psensor_switch.o
